remote_theme: mmistakes/minimal-mistakes
locale: "en-US"
plugins:
  - jekyll-include-cache

# This creates the "Cards" for your projects
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "single"
      author_profile: true
      share: true
